[package]
name = "tokay"
version = "0.5.0"
description = "Tokay is a programming language designed for ad-hoc parsing, inspired by awk."
authors = ["Jan Max Meyer <jmm@phorward.de>"]
homepage = "https://tokay.dev/"
repository = "https://github.com/tokay-lang/tokay/"
license = "MIT"
edition = "2021"
categories = [
    "parsing",
    "compilers",
    "command-line-utilities",
    "development-tools"
]
keywords = [
    "awk",
    "dsl",
    "packrat",
    "parser",
    "vm"
]

[features]
default = ["static_expression_evaluation"]
static_expression_evaluation = []  # Evaluates static expressions like 1+2+3 during compile-time to reduce resulting operations

[build-dependencies]
tokay = "0.4"
glob = "0.3.0"

[dependencies]
indexmap = "1.8.1"
macros = { path = "macros" }
clap = { version = "2", features = ["yaml"] }
rustyline = "8.2.0"
charclass = "0.1"
