[package]
name = "tokay"
version = "0.3.0"
description = "Tokay, a programming language dedicated to parsing and text-processing."
authors = ["Jan Max Meyer <jmm@phorward.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["static_expression_evaluation"]
static_expression_evaluation = []  # Evaluates static expressions like 1+2+3 during compile-time to reduce resulting operations

[dependencies]
clap = { version = "2", features = ["yaml"] }
