[package]
name = "tokay"
version = "0.2.0"
authors = ["Jan Max Meyer <jmm@phorward.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
