[package]
name = "tokay"
version = "0.4.0"
description = "Tokay is a programming language dedicated to parsing and text-processing."
authors = ["Jan Max Meyer <jmm@phorward.de>"]
homepage = "https://tokay.dev/"
repository = "https://github.com/phorward/tokay/"
license = "MIT"
edition = "2021"

[features]
default = ["static_expression_evaluation"]
static_expression_evaluation = []  # Evaluates static expressions like 1+2+3 during compile-time to reduce resulting operations

[dependencies]
clap = { version = "2", features = ["yaml"] }
rustyline = "8.2.0"
inventory = "0.1"
charclass = { git = "https://github.com/phorward/charclass" }
