[package]
name = "tokay"
version = "0.5.0"
description = "Tokay is a programming language dedicated to parsing and text-processing."
authors = ["Jan Max Meyer <jmm@phorward.de>"]
homepage = "https://tokay.dev/"
repository = "https://github.com/tokay-lang/tokay/"
license = "MIT"
edition = "2021"

[features]
default = ["static_expression_evaluation"]
static_expression_evaluation = []  # Evaluates static expressions like 1+2+3 during compile-time to reduce resulting operations

[dependencies]
macros = { path = "macros" }
clap = { version = "2", features = ["yaml"] }
rustyline = "8.2.0"
linkme = "0.2"
charclass = "0.1"

# codegen-units is set to 1 as workaround for the issues
# https://github.com/dtolnay/linkme/issues/31
# https://github.com/dtolnay/inventory/issues/32
#

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1
